### PR TITLE
Added Ready2Go MPLAB X Project

### PR DESCRIPTION
**Pull request by wantedxnn**

### CODE REVIEW

**Comment by wantedxnn** [comment]
I'm not expert in using github.. but i hope it's ok 😋

**Comment by bjerrep** [comment]
Wow ! You made it build ! Thats so nice to see. Good work ! Cool that the
binary matches.

If you dont want to spend more time with this project then I will be happy
to merge as is. Just let me know.

I do however have some comments if you want to perhaps make it look a
little nicer.

First of all its all in git so dont be afraid of deleting old stuff and so
on. Everything can always be retrieved again.
So I would suggest that you delete the files I added and then dump your
sources in the root instead. Then there will be
the working sources and the mplabx directory which would be prettier I
think.

You have also submitted binaries, both the final images and also
intermediate .o object files. They dont really belong in git.
If mplab have a "clean project" then try to run that, then I guess it will
look a lot cleaner. I can see there is a private directory
this might disappear in a clean as well.

The exception is that perhaps the .hex should be available in the root as
this is probably the most interesting for any visitors.

With such a cleaned up repository you can make a new commit.

Then make a build, and everything that turns up in a git status should now
be added to a ".gitignore" file in the root so
that git will forever ignore all the binary files. And then commit the
.gitignore file.

Also if you feel like it then make a new README.md file. There might be a
version for mplab and build instructions
unless they are so obvious that it doesnt make sense. Perhaps a picture and
what not. Just if you think it could
be funny.

Please let me know what you think

~Claus

**Comment by wantedxnn** [comment]
It's not a problem for files.. is compiled in VM (Virtual Box) so you can leave as is 😁

**Comment by bjerrep** [comment]
Cleaning postponed :-)

**Pull request merged**
